import { Routes } from '@angular/router';
import { LoginComponent } from './auth/login.component';
import { authGuard } from './auth/auth.guard';
import { hrmAccessGuard } from './auth/hrm-access.guard';
import { AppShellComponent } from './shell/app-shell.component';

export const routes: Routes = [
  { path: 'login', component: LoginComponent },
  {
    path: '',
    component: AppShellComponent,
    canActivate: [authGuard],
    children: [
      { path: 'dashboard', loadComponent: () => import('./dashboard/dashboard.component').then(m => m.DashboardComponent), data: { sysType: '1' } },
      { path: 'dept-ot-apply-info', loadComponent: () => import('./dept-ot-apply-info/dept-ot-apply-info.component').then(m => m.DeptOtApplyInfoComponent) },
      { path: 'manage-emp-position-info', loadComponent: () => import('./manage-emp-position-info/manage-emp-position-info.component').then(m => m.ManageEmpPositionInfoComponent) },
      { path: 'manage-count-info', loadComponent: () => import('./manage-count-info/manage-count-info.component').then(m => m.ManageCountInfoComponent) },
      { path: 'evs-result-emp', loadComponent: () => import('./evs-result-emp/evs-result-emp.component').then(m => m.EvsResultEmpComponent) },
      { path: 'manage-evs-result-emp', loadComponent: () => import('./manage-evs-result-emp/manage-evs-result-emp.component').then(m => m.ManageEvsResultEmpComponent) },
      { path: 'hr-card-info', loadComponent: () => import('./hr-card-info/hr-card-info.component').then(m => m.HrCardInfoComponent) },
      { path: 'view-personal-info', loadComponent: () => import('./view-personal-info/view-personal-info.component').then(m => m.ViewPersonalInfoComponent) },
      { path: 'pa-month-person-info', loadComponent: () => import('./pa-month-person-info/pa-month-person-info.component').then(m => m.PaMonthPersonInfoComponent) },
      { path: 'change-user', loadComponent: () => import('./change-user/change-user.component').then(m => m.ChangeUserComponent) },
      { path: 'personal-info', loadComponent: () => import('./personal-info/personal-info.component').then(m => m.PersonalInfoComponent) },
      { path: 'work-info', loadComponent: () => import('./work-info/work-info.component').then(m => m.WorkInfoComponent) },
      { path: 'qualification-info', loadComponent: () => import('./qualification-info/qualification-info.component').then(m => m.QualificationInfoComponent) },
      { path: 'apply-info', loadComponent: () => import('./apply-info/apply-info.component').then(m => m.ApplyInfoComponent) },
      { path: 'hrm-approve-apply-info', loadComponent: () => import('./hrm-approve-apply-info/hrm-approve-apply-info.component').then(m => m.HrmApproveApplyInfoComponent), canActivate: [hrmAccessGuard], data: { sysType: '0' } },
      { path: 'hrm-dashboard', loadComponent: () => import('./hrm-dashboard/hrm-dashboard.component').then(m => m.HrmDashboardComponent), canActivate: [hrmAccessGuard], data: { sysType: '0' } },
      { path: 'apply-attendance-batch-info', loadComponent: () => import('./apply-attendance-batch-info/apply-attendance-batch-info.component').then(m => m.ApplyAttendanceBatchInfoComponent) },
      { path: 'ot-apply-batch-info', loadComponent: () => import('./ot-apply-batch-info/ot-apply-batch-info.component').then(m => m.OtApplyBatchInfoComponent) },
      { path: 'attendance-ex-batch-info', loadComponent: () => import('./attendance-ex-batch-info/attendance-ex-batch-info.component').then(m => m.AttendanceExBatchInfoComponent) },
      { path: 'check-attendance-ex-for-batch', loadComponent: () => import('./check-attendance-ex-for-batch/check-attendance-ex-for-batch.component').then(m => m.CheckAttendanceExForBatchComponent) },
      { path: 'coord-apply-attendance-info', loadComponent: () => import('./coord-apply-attendance-info/coord-apply-attendance-info.component').then(m => m.CoordApplyAttendanceInfoComponent) },
      { path: 'coord-apply-ot-info-list', loadComponent: () => import('./coord-apply-ot-info-list/coord-apply-ot-info-list.component').then(m => m.CoordApplyOtInfoListComponent) },
      { path: 'ess-view-emp-calendar', loadComponent: () => import('./ess-view-emp-calendar/ess-view-emp-calendar.component').then(m => m.EssViewEmpCalendarComponent) },
      { path: 'view-ot-report', loadComponent: () => import('./view-ot-report/view-ot-report.component').then(m => m.ViewOtReportComponent) },
      { path: 'view-ar-personal-list', loadComponent: () => import('./view-ar-personal-list/view-ar-personal-list.component').then(m => m.ViewArPersonalListComponent) },
      { path: 'view-ot-apply-personal-list', loadComponent: () => import('./view-ot-apply-personal-list/view-ot-apply-personal-list.component').then(m => m.ViewOtApplyPersonalListComponent) },
      { path: 'view-class-calendar', loadComponent: () => import('./view-class-calendar/view-class-calendar.component').then(m => m.ViewClassCalendarComponent) },
      { path: 'view-ar-card-record', loadComponent: () => import('./view-ar-card-record/view-ar-card-record.component').then(m => m.ViewArCardRecordComponent) },
      { path: 'view-ar-card-record-day', loadComponent: () => import('./view-ar-card-record-day/view-ar-card-record-day.component').then(m => m.ViewArCardRecordDayComponent) },
      { path: 'view-ar-card-record-meal', loadComponent: () => import('./view-ar-card-record-meal/view-ar-card-record-meal.component').then(m => m.ViewArCardRecordMealComponent) },
      { path: 'view-ar-card-record-for-self', loadComponent: () => import('./view-ar-card-record-for-self/view-ar-card-record-for-self.component').then(m => m.ViewArCardRecordForSelfComponent) },
      { path: 'view-entry-info-list', loadComponent: () => import('./view-entry-info-list/view-entry-info-list.component').then(m => m.ViewEntryInfoListComponent) },
      { path: 'view-month-detail-list', loadComponent: () => import('./view-month-detail-list/view-month-detail-list.component').then(m => m.ViewMonthDetailListComponent) },
      { path: 'view-year-use-info-list', loadComponent: () => import('./view-year-use-info-list/view-year-use-info-list.component').then(m => m.ViewYearUseInfoListComponent) },
      { path: 'workgroup-exper-list', loadComponent: () => import('./workgroup-exper-list/workgroup-exper-list.component').then(m => m.WorkgroupExperListComponent) },
      { path: 'person-shift-list', loadComponent: () => import('./person-shift-list/person-shift-list.component').then(m => m.PersonShiftListComponent) },
      { path: 'sst-apply-attendance', loadComponent: () => import('./sst-apply-attendance/sst-apply-attendance.component').then(m => m.SstApplyAttendanceComponent) },
      { path: 'apply-attendance-info-list', loadComponent: () => import('./apply-attendance-info-list/apply-attendance-info-list.component').then(m => m.ApplyAttendanceInfoListComponent) },
      { path: 'sst-ot-apply-info', loadComponent: () => import('./sst-ot-apply-info/sst-ot-apply-info.component').then(m => m.SstOtApplyInfoComponent) },
      { path: 'ot-apply-info-list', loadComponent: () => import('./ot-apply-info-list/ot-apply-info-list.component').then(m => m.OtApplyInfoListComponent) },
      { path: 'cwa-abnormal-apply', loadComponent: () => import('./cwa-abnormal-apply/cwa-abnormal-apply.component').then(m => m.CwaAbnormalApplyComponent) },
      { path: 'apply-leave-info-list', loadComponent: () => import('./apply-leave-info-list/apply-leave-info-list.component').then(m => m.ApplyLeaveInfoListComponent) },
      { path: 'attendance-personal-info-list', loadComponent: () => import('./attendance-personal-info-list/attendance-personal-info-list.component').then(m => m.AttendancePersonalInfoListComponent) },
      { path: 'person-ot-apply-info-list', loadComponent: () => import('./person-ot-apply-info-list/person-ot-apply-info-list.component').then(m => m.PersonOtApplyInfoListComponent) },
      { path: 'view-ar-personal-self-list', loadComponent: () => import('./view-ar-personal-self-list/view-ar-personal-self-list.component').then(m => m.ViewArPersonalSelfListComponent) },
      { path: 'view-ot-apply-personal-self-list', loadComponent: () => import('./view-ot-apply-personal-self-list/view-ot-apply-personal-self-list.component').then(m => m.ViewOtApplyPersonalSelfListComponent) },
      { path: 'year-use-info', loadComponent: () => import('./year-use-info/year-use-info.component').then(m => m.YearUseInfoComponent) },
      { path: 'reg-personal-target', loadComponent: () => import('./reg-personal-target/reg-personal-target.component').then(m => m.RegPersonalTargetComponent) },
      { path: 'evs-resume-list', loadComponent: () => import('./evs-resume-list/evs-resume-list.component').then(m => m.EvsResumeListComponent) },
      { path: 'evs-schedule-panel', loadComponent: () => import('./evs-schedule-panel/evs-schedule-panel.component').then(m => m.EvsSchedulePanelComponent) },
      { path: 'evs-param-panel', loadComponent: () => import('./evs-param-panel/evs-param-panel.component').then(m => m.EvsParamPanelComponent) },
      { path: 'evs-distribution-rate-panel', loadComponent: () => import('./evs-distribution-rate-panel/evs-distribution-rate-panel.component').then(m => m.EvsDistributionRatePanelComponent) },
      { path: 'evs-affirmor-setup', loadComponent: () => import('./evs-affirmor-setup/evs-affirmor-setup.component').then(m => m.EvsAffirmorSetupComponent) },
      { path: 'evs-result', loadComponent: () => import('./evs-result/evs-result.component').then(m => m.EvsResultComponent) },
      { path: 'evs-item-panel', loadComponent: () => import('./evs-item-panel/evs-item-panel.component').then(m => m.EvsItemPanelComponent) },
      { path: 'evs-formula-list', loadComponent: () => import('./evs-formula-list/evs-formula-list.component').then(m => m.EvsFormulaListComponent) },
      { path: 'confirm-target1', loadComponent: () => import('./confirm-target1/confirm-target1.component').then(m => m.ConfirmTarget1Component) },
      { path: 'confirm-target2', loadComponent: () => import('./confirm-target2/confirm-target2.component').then(m => m.ConfirmTarget2Component) },
      { path: 'evs-by-self-htsv', loadComponent: () => import('./evs-by-self-htsv/evs-by-self-htsv.component').then(m => m.EvsBySelfHtsvComponent) },
      { path: 'affirm-target1', loadComponent: () => import('./affirm-target1/affirm-target1.component').then(m => m.AffirmTarget1Component) },
      { path: 'affirm-target2', loadComponent: () => import('./affirm-target2/affirm-target2.component').then(m => m.AffirmTarget2Component) },
      { path: 'evs-by-self-sst-ability', loadComponent: () => import('./evs-by-self-sst-ability/evs-by-self-sst-ability.component').then(m => m.EvsBySelfSSTAbilityComponent) },
      { path: 'affirm-target1-ability', loadComponent: () => import('./affirm-target1-ability/affirm-target1-ability.component').then(m => m.AffirmTarget1AbilityComponent) },
      { path: 'affirm-target2-ability', loadComponent: () => import('./affirm-target2-ability/affirm-target2-ability.component').then(m => m.AffirmTarget2AbilityComponent) },
      { path: 'view-approval-email', loadComponent: () => import('./view-approval-email/view-approval-email.component').then(m => m.ViewApprovalEmailComponent) },
      { path: 'view-approvaled-email', loadComponent: () => import('./view-approvaled-email/view-approvaled-email.component').then(m => m.ViewApprovaledEmailComponent) },
      { path: 'view-noticeed-email', loadComponent: () => import('./view-noticeed-email/view-noticeed-email.component').then(m => m.ViewNoticeedEmailComponent) },
      { path: 'view-temp-emp-info-list', loadComponent: () => import('./view-temp-emp-info-list/view-temp-emp-info-list.component').then(m => m.ViewTempEmpInfoListComponent), data: { sysType: '0' } },
      { path: 'work-experience-info', loadComponent: () => import('./work-experience-info/work-experience-info.component').then(m => m.WorkExperienceInfoComponent) },
      { path: 'emergency-address-info', loadComponent: () => import('./emergency-address-info/emergency-address-info.component').then(m => m.EmergencyAddressInfoComponent) },
      { path: 'address-info', loadComponent: () => import('./address-info/address-info.component').then(m => m.AddressInfoComponent) },
      { path: 'family-info', loadComponent: () => import('./family-info/family-info.component').then(m => m.FamilyInfoComponent) },
      { path: 'education-info', loadComponent: () => import('./education-info/education-info.component').then(m => m.EducationInfoComponent) },
      { path: 'recognition-info', loadComponent: () => import('./recognition-info/recognition-info.component').then(m => m.RecognitionInfoComponent) },
      { path: 'punishment-info', loadComponent: () => import('./punishment-info/punishment-info.component').then(m => m.PunishmentInfoComponent) },
      { path: 'manage-qualification-info', loadComponent: () => import('./manage-qualification-info/manage-qualification-info.component').then(m => m.ManageQualificationInfoComponent) },
      { path: 'contract-info-list', loadComponent: () => import('./contract-info-list/contract-info-list.component').then(m => m.ContractInfoListComponent) },
      { path: 'expired-contract-list', loadComponent: () => import('./expired-contract-list/expired-contract-list.component').then(m => m.ExpiredContractListComponent) },
      { path: 'contract-info-search', loadComponent: () => import('./contract-info-search/contract-info-search.component').then(m => m.ContractInfoSearchComponent) },
      { path: 'contract-change-list', loadComponent: () => import('./contract-change-list/contract-change-list.component').then(m => m.ContractChangeListComponent) },
      { path: 'view-recruit-list', loadComponent: () => import('./view-recruit-list/view-recruit-list.component').then(m => m.ViewRecruitListComponent) },
      { path: 'view-recruit-batch-list', loadComponent: () => import('./view-recruit-batch-list/view-recruit-batch-list.component').then(m => m.ViewRecruitBatchListComponent) },
      { path: 'view-start-point', loadComponent: () => import('./view-start-point/view-start-point.component').then(m => m.ViewStartPointComponent) },
      { path: 'view-experience-batch-list', loadComponent: () => import('./view-experience-batch-list/view-experience-batch-list.component').then(m => m.ViewExperienceBatchListComponent) },
      { path: 'photo-import', loadComponent: () => import('./photo-import/photo-import.component').then(m => m.PhotoImportComponent) },
      { path: 'view-cycle-parameter', loadComponent: () => import('./view-cycle-parameter/view-cycle-parameter.component').then(m => m.ViewCycleParameterComponent) },
      { path: 'view-cycle', loadComponent: () => import('./view-cycle/view-cycle.component').then(m => m.ViewCycleComponent) },
      { path: 'view-pa-pay-schedule', loadComponent: () => import('./view-pa-pay-schedule/view-pa-pay-schedule.component').then(m => m.ViewPaPayScheduleComponent) },
      { path: 'view-salary-code', loadComponent: () => import('./view-salary-code/view-salary-code.component').then(m => m.ViewSalaryCodeComponent) },
      { path: 'view-pa-input-item-param', loadComponent: () => import('./view-pa-input-item-param/view-pa-input-item-param.component').then(m => m.ViewPaInputItemParamComponent) },
      { path: 'view-pa-input-item-data', loadComponent: () => import('./view-pa-input-item-data/view-pa-input-item-data.component').then(m => m.ViewPaInputItemDataComponent) },
      { path: 'view-pa-compute-item-param-list', loadComponent: () => import('./view-pa-compute-item-param-list/view-pa-compute-item-param-list.component').then(m => m.ViewPaComputeItemParamListComponent) },
      { path: 'view-pa-pay-obj', loadComponent: () => import('./view-pa-pay-obj/view-pa-pay-obj.component').then(m => m.ViewPaPayObjComponent) },
      { path: 'view-pa-emp-account', loadComponent: () => import('./view-pa-emp-account/view-pa-emp-account.component').then(m => m.ViewPaEmpAccountComponent) },
      { path: 'view-pa-pay-stub', loadComponent: () => import('./view-pa-pay-stub/view-pa-pay-stub.component').then(m => m.ViewPaPayStubComponent) },
      { path: 'view-pa-result', loadComponent: () => import('./view-pa-result/view-pa-result.component').then(m => m.ViewPaResultComponent) },
      { path: 'view-pa-supervisor', loadComponent: () => import('./view-pa-supervisor/view-pa-supervisor.component').then(m => m.ViewPaSupervisorComponent) },
      { path: 'view-dynamic-group', loadComponent: () => import('./view-dynamic-group/view-dynamic-group.component').then(m => m.ViewDynamicGroupComponent) },
      { path: 'add-emp-shift', loadComponent: () => import('./add-emp-shift/add-emp-shift.component').then(m => m.AddEmpShiftComponent) },
      { path: 'view-ar-item', loadComponent: () => import('./view-ar-item/view-ar-item.component').then(m => m.ViewArItemComponent) },
      { path: 'view-ar-item-param-list', loadComponent: () => import('./view-ar-item-param-list/view-ar-item-param-list.component').then(m => m.ViewArItemParamListComponent) },
      { path: 'view-item-parameter', loadComponent: () => import('./view-item-parameter/view-item-parameter.component').then(m => m.ViewItemParameterComponent) },
      { path: 'view-shift', loadComponent: () => import('./view-shift/view-shift.component').then(m => m.ViewShiftComponent) },
      { path: 'view-statutory-holidays', loadComponent: () => import('./view-statutory-holidays/view-statutory-holidays.component').then(m => m.ViewStatutoryHolidaysComponent) },
      { path: 'view-company-calendar', loadComponent: () => import('./view-company-calendar/view-company-calendar.component').then(m => m.ViewCompanyCalendarComponent) },
      { path: 'view-emp-calendar', loadComponent: () => import('./view-emp-calendar/view-emp-calendar.component').then(m => m.ViewEmpCalendarComponent) },
      { path: 'view-ar-shift-group-list', loadComponent: () => import('./view-ar-shift-group-list/view-ar-shift-group-list.component').then(m => m.ViewArShiftGroupListComponent) },
      { path: 'view-summary-param-item', loadComponent: () => import('./view-summary-param-item/view-summary-param-item.component').then(m => m.ViewSummaryParamItemComponent) },
      { path: 'view-summary-item', loadComponent: () => import('./view-summary-item/view-summary-item.component').then(m => m.ViewSummaryItemComponent) },
      { path: 'view-summary-formula', loadComponent: () => import('./view-summary-formula/view-summary-formula.component').then(m => m.ViewSummaryFormulaComponent) },
      { path: 'view-pa-formula', loadComponent: () => import('./view-pa-formula/view-pa-formula.component').then(m => m.ViewPaFormulaComponent) },
      { path: 'view-attendance-keeper', loadComponent: () => import('./view-attendance-keeper/view-attendance-keeper.component').then(m => m.ViewAttendanceKeeperComponent) },
      { path: 'view-depart-manager-list', loadComponent: () => import('./view-depart-manager-list/view-depart-manager-list.component').then(m => m.ViewDepartManagerListComponent) },
      { path: 'attendance-search', loadComponent: () => import('./attendance-search/attendance-search.component').then(m => m.AttendanceSearchComponent) },
      { path: 'search-apply-ot-info-list', loadComponent: () => import('./search-apply-ot-info-list/search-apply-ot-info-list.component').then(m => m.SearchApplyOtInfoListComponent) },
      { path: 'view-vac-emp-list', loadComponent: () => import('./view-vac-emp-list/view-vac-emp-list.component').then(m => m.ViewVacEmpListComponent) },
      { path: 'view-ar-detail-calculate', loadComponent: () => import('./view-ar-detail-calculate/view-ar-detail-calculate.component').then(m => m.ViewArDetailCalculateComponent) },
      { path: 'attendance-ex-confirm', loadComponent: () => import('./attendance-ex-confirm/attendance-ex-confirm.component').then(m => m.AttendanceExConfirmComponent) },
      { path: 'leave-confirm', loadComponent: () => import('./leave-confirm/leave-confirm.component').then(m => m.LeaveConfirmComponent) },
      { path: 'view-pa-work-flow', loadComponent: () => import('./view-pa-work-flow/view-pa-work-flow.component').then(m => m.ViewPaWorkFlowComponent) },
      { path: 'view-resume-list', loadComponent: () => import('./view-resume-list/view-resume-list.component').then(m => m.ViewResumeListComponent) },
      { path: 'view-resume-process', loadComponent: () => import('./view-resume-process/view-resume-process.component').then(m => m.ViewResumeProcessComponent) },
      { path: 'view-compose-org', loadComponent: () => import('./view-compose-org/view-compose-org.component').then(m => m.ViewComposeOrgComponent) },
      { path: 'view-org-business', loadComponent: () => import('./view-org-business/view-org-business.component').then(m => m.ViewOrgBusinessComponent) },
      { path: 'view-org-cost-center', loadComponent: () => import('./view-org-cost-center/view-org-cost-center.component').then(m => m.ViewOrgCostCenterComponent) },
      { path: 'view-dept-manager-check', loadComponent: () => import('./view-dept-manager-check/view-dept-manager-check.component').then(m => m.ViewDeptManagerCheckComponent) },
      { path: 'view-current-org-info', loadComponent: () => import('./view-current-org-info/view-current-org-info.component').then(m => m.ViewCurrentOrgInfoComponent) },
      { path: 'view-org-info', loadComponent: () => import('./view-org-info/view-org-info.component').then(m => m.ViewOrgInfoComponent) },
      { path: 'view-history-org-info', loadComponent: () => import('./view-history-org-info/view-history-org-info.component').then(m => m.ViewHistoryOrgInfoComponent) },
      { path: 'view-menu-list', loadComponent: () => import('./view-menu-list/view-menu-list.component').then(m => m.ViewMenuListComponent) },
      { path: 'view-menu-param-list', loadComponent: () => import('./view-menu-param-list/view-menu-param-list.component').then(m => m.ViewMenuParamListComponent) },
      { path: 'view-code-manage', loadComponent: () => import('./view-code-manage/view-code-manage.component').then(m => m.ViewCodeManageComponent) },
      { path: 'view-company', loadComponent: () => import('./view-company/view-company.component').then(m => m.ViewCompanyComponent) },
      { path: 'view-code-param-list', loadComponent: () => import('./view-code-param-list/view-code-param-list.component').then(m => m.ViewCodeParamListComponent) },
      { path: 'view-roles-group', loadComponent: () => import('./view-roles-group/view-roles-group.component').then(m => m.ViewRolesGroupComponent) },
      { path: 'view-roles-group-list', loadComponent: () => import('./view-roles-group-list/view-roles-group-list.component').then(m => m.ViewRolesGroupListComponent) },
      { path: 'view-login-user', loadComponent: () => import('./view-login-user/view-login-user.component').then(m => m.ViewLoginUserComponent) },
      { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
    ],
  },
  { path: '**', redirectTo: 'login' },
];
