spring.application.name=HR-11
spring.datasource.url=jdbc:oracle:thin:@14.225.17.145:1521:orcl
spring.datasource.username=HTSV_HR
spring.datasource.password=htsvhrdb
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
mybatis.mapper-locations=classpath:com/ait/mapper/*.xml
mybatis.type-aliases-package=com.ait
logging.level.com.ait.ar=INFO
logging.level.com.ait.hrm=INFO
logging.level.com.ait.org=INFO
logging.level.com.ait.sy=INFO
logging.level.org.springframework=WARN
